app = "vlach-cookbook-backup"
primary_region = "sea"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = "requests"
    hard_limit = 50
    soft_limit = 40

  [[http_service.checks]]
    grace_period = "2s"
    interval = "30s"
    method = "GET"
    path = "/health"
    timeout = "2s"

[[vm]]
  size = "shared-cpu-1x"
  memory = "256mb"
