# Set the version of docker compose to use
version: '3.9'

# The containers that compose the project
services:
  web:
    build: .
    ports:
      - '4321:4321'
    environment:
      DATABASE_URL: 'postgresql://prisma:prisma@db:5432/tests'
      PORT: 4321
  db:
    image: postgres:16
    restart: always
    container_name: e2e-tests
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: tests
