# Use `-a vlach-cookbook` to deploy the production app.
# Production releases use `sed` to set min_machines_running to 1.
app = "vlach-cookbook-staging"
primary_region = "sea"
kill_signal = "SIGINT"
kill_timeout = 5

[env]
  PORT = "8080"

[deploy]
  release_command = "pnpm fly-release-command"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "suspend"
  auto_start_machines = true
  min_machines_running = 0
  [http_service.concurrency]
    type = "requests"
    soft_limit = 200
    hard_limit = 250
  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    timeout = "5s"
    method = "GET"
    path = "/"

[[vm]]
  size = "shared-cpu-1x"
  memory = "512mb"
