name: Backup Database
concurrency: backup
on:
  schedule:
    - cron: "14 7,19 * * *"
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Start a backup
      run: 'curl --fail-with-body -X POST --header "Authorization: Bearer $START_BACKUP_PASSWORD" https://vlach-cookbook-backup.fly.dev/backup'
      env:
        START_BACKUP_PASSWORD: ${{ secrets.START_BACKUP_PASSWORD }}
