name: Playwright Tests
on:
  - push
  - pull_request
defaults:
  run:
    working-directory: webserver
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 7
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'pnpm'
        cache-dependency-path: 'webserver/pnpm-lock.yaml'
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
    - name: Cache Playwright Browsers
      uses: actions/cache@v3
      with:
        path: '~/.cache/ms-playwright'
        key: ${{ hashFiles('webserver/pnpm-lock.yaml') }}
    - name: Install Playwright Browsers
      run: pnpm exec playwright install --with-deps
    - name: Start Docker Compose services
      uses: isbang/compose-action@v1.4.1
      with:
        compose-file: 'webserver/docker-compose.yml'
        services: |
          db
    - name: Initialize Prisma and DB
      run: pnpm dotenv -e .env.test -- pnpm prisma db push --force-reset
    - name: Build
      run: pnpm run build
    - name: Run Playwright tests
      run: pnpm dotenv -e .env.test -- pnpm exec playwright test
      env:
        DEBUG: "pw:webserver"
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: test-results
        path: webserver/test-results/
        retention-days: 30
