name: Deploy to Production
concurrency: production
on:
  release:
    types: [released]
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: "https://cookbook.vlach.us/"
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Upload commits to Sentry release
      uses: getsentry/action-release@v1
      env:
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        SENTRY_ORG: jeffrey-yasskin
        SENTRY_PROJECT: vlach-cookbook
      with:
        environment: production
        finalize: false
        version: ${{ github.ref_name }}
        version_prefix: 'vlach-cookbook@'
        set_commits: auto
    - uses: superfly/flyctl-actions/setup-flyctl@master
    - name: Update the production deployment.
      run: |
        flyctl deploy webserver -a vlach-cookbook \
          --build-arg GOOGLE_SITE_VERIFICATION="$GOOGLE_SITE_VERIFICATION" \
          --build-arg SENTRY_DSN="$SENTRY_DSN" \
          --build-secret SENTRY_AUTH_TOKEN="$SENTRY_AUTH_TOKEN" \
          --build-arg SENTRY_RELEASE="vlach-cookbook@$RELEASE_NAME" \
          --build-arg SENTRY_ENVIRONMENT=production
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        GOOGLE_SITE_VERIFICATION: ${{ vars.GOOGLE_SITE_VERIFICATION }}
        SENTRY_DSN: ${{ vars.SENTRY_DSN }}
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        RELEASE_NAME: ${{ github.ref_name }}
        NO_COLOR: 1
