name: Deploy to Production
concurrency: production
on:
  release:
    types: [released]
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: "https://cookbook.vlach.us/"
    steps:
    - uses: actions/checkout@v4
    - uses: superfly/flyctl-actions/setup-flyctl@master
    - name: Update the production deployment.
      run: flyctl deploy webserver -a vlach-cookbook --build-arg GOOGLE_SITE_VERIFICATION="$GOOGLE_SITE_VERIFICATION"
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        GOOGLE_SITE_VERIFICATION: ${{ vars.GOOGLE_SITE_VERIFICATION }}
        NO_COLOR: 1
