name: Deploy to Production
concurrency: production
on:
  release:
    types: [released]
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: "https://vlach-cookbook.fly.dev/"
    steps:
    - uses: actions/checkout@v3
    - uses: superfly/flyctl-actions/setup-flyctl@master
    - name: Update the production deployment.
      run: flyctl deploy webserver -a vlach-cookbook
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        NO_COLOR: 1
