name: Deploy to Staging
on:
  workflow_run:
    workflows: [Tests]
    branches: [main]
    types: [completed]
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: "https://vlach-cookbook-staging.fly.dev/"
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - uses: actions/checkout@v3
    - uses: superfly/flyctl-actions/setup-flyctl@master
    - name: Build the image.
      run: flyctl deploy --remote-only --image-label ${{ github.sha }} --build-only --push webserver
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        NO_COLOR: 1
    - name: Update the machine's image.
      run: flyctl image update --image registry.fly.io/vlach-cookbook-staging:${{ github.sha }} -a vlach-cookbook-staging --yes
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
